apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-service
  name: postgresql-service
spec:
  externalName: nhat-rds-perntodo.cv6mqsa5xbzj.us-west-1.rds.amazonaws.com
  selector:
    app: postgresql-service
  type: ExternalName
status:
  loadBalancer: {}